name: Build and Deploy Azure Function (Java)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # =====================================================
  # JOB 1 - BUILD
  # =====================================================
  build:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Azure Function
        run: mvn clean package -DskipTests  

      - name: Create Deployment Package
        # Entramos na pasta gerada pelo maven e zipamos o conte√∫do interno
        run: |
          cd target/azure-functions/*/
          rm -f local.settings.json
          zip -r ../../../function-deploy.zip .
          
      - name: Upload function package
        uses: actions/upload-artifact@v4
        with:
          name: function-artifact # Nome do artefato no GitHub
          path: function-deploy.zip
            
  # =====================================================
  # JOB 2 - DEPLOY
  # =====================================================
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name:  function-artifact
          
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Configure Environment Variables'
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ vars.FUNCTION_APP_NAME }}
          app-settings-json: |
            [
              {
                "name": "URL_FUNC_PRIVATE",
                "value": "${{ secrets.URL_FUNC_PRIVATE }}",
                "slotSetting": false
              },
              {
                "name": "INTERNAL_SECRET_TOKEN",
                "value": "${{ secrets.INTERNAL_SECRET_TOKEN }}",
                "slotSetting": false
              }
            ]

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ vars.FUNCTION_APP_NAME }}
          package: './function-deploy.zip'
          
